# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [2]:
import numpy as np

#### Create an array of 10 zeros 

In [5]:
lis0=np.zeros(11)

In [6]:
lis

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [7]:
lis1=np.ones(11)

In [8]:
lis1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [10]:
lis5 = np.arange(11)
lis5[:11] = 5

In [11]:
lis5

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

#### Create an array of the integers from 10 to 50

In [16]:
lisa = np.arange(10,51)

In [17]:
lisa

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [18]:
lisaa = np.arange(10,51,2)

In [19]:
lisaa

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [25]:
mat = [[0,1,2],[3,4,5],[6,7,8]]

In [26]:
np.array(mat)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [28]:
eyee = np.eye(3)

In [29]:
eyee

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [36]:
lis = np.random.rand(1)

In [37]:
lis

array([0.37104174])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [42]:
lisss = np.random.rand(5,5)

In [43]:
lisss

array([[0.62066812, 0.0557645 , 0.14493584, 0.27845512, 0.89873385],
       [0.83597514, 0.34526468, 0.26430498, 0.18715836, 0.1211697 ],
       [0.82618295, 0.74128782, 0.74578513, 0.84446351, 0.28872243],
       [0.8925108 , 0.38677003, 0.44711318, 0.62294986, 0.17378957],
       [0.2270192 , 0.98183587, 0.75995909, 0.23545492, 0.82391816]])

#### Create the following matrix:

In [58]:
lisr = np.random.randn(5,5)

In [59]:
lisr

array([[ 0.15439742,  0.42483562, -0.28446454,  1.39521778, -2.14186075],
       [ 0.06529682,  0.32295797, -1.12631256,  1.17582791,  1.20463468],
       [-0.35646819, -0.52322131,  1.08928877, -1.27172984,  0.53859446],
       [-0.7723889 , -0.84551367, -0.34706426, -0.47395197,  0.57894096],
       [ 0.31915156,  0.67128507, -1.00892883,  0.34538182, -2.3046448 ]])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [69]:
lisrr = np.random.randn(5,4)

In [70]:
lisrr

array([[-1.5849249 , -0.01715431,  0.1299676 , -1.65902462],
       [ 0.10667237,  1.14867311, -0.93946718,  0.53113436],
       [-0.00567251, -1.84763063,  1.2563636 ,  0.51464192],
       [-1.62320698,  1.25057428,  0.5258255 ,  1.66782873],
       [ 0.18730323,  0.55949658,  1.75066005, -0.39555601]])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [182]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [183]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [184]:
mat[3,4]

20

In [185]:
mat[:3,1:3:2]

array([[ 2],
       [ 7],
       [12]])

In [186]:
mat[4]

array([21, 22, 23, 24, 25])

In [187]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [188]:
np.sum(mat)

325

#### Get the standard deviation of the values in mat

In [194]:
np.sqrt(325)

18.027756377319946

In [196]:
mat = (325 * 2 * np.pi) / 360
mat

5.672320068981571

#### Get the sum of all the columns in mat

In [179]:

np.sum(mat,axis=0)

array([55, 60, 65, 70, 75])

# Great Job!